### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by lazir0lufias** [hendrycks/math#11]
Hi, sorry im new in this field.

!python tune_gpt.py --khan-dataroot /content/amps/khan/ --save-dir /content/drive/MyDrive/model/

when i using the above code on google colap, i got error

Traceback (most recent call last):
  File "tune_gpt.py", line 333, in <module>
    main()
  File "tune_gpt.py", line 318, in main
    train_data = get_dataset(args)
  File "tune_gpt.py", line 239, in get_dataset
    len_multiplier, dirname = args.khan_dataroot.split("@")
ValueError: not enough values to unpack (expected 2, got 1)

How to fix this?

**Comment by hendrycks** [comment]
On colab there must not have been a directory name, as directories on drive
might be structured unusually.

Best,
Dan Hendrycks

**Comment by lazir0lufias** [comment]
free drive just 15gb but amps 23gb, how can i edit the scripts so that can be trained on colap ?

**Comment by g-lopes** [comment]
I have the same problem here. I am running it on my machine, not on colab. Any ideas?

**Comment by ayaka14732** [comment]
I believe that dataroot is the path to the directories, i.e. `/home/gui/dev/t5math/data/amps/mathematica`, not a list of files.

**Comment by ayaka14732** [comment]
I understand the problem now. It should be

```
python t5_tune.py \
  --mathematica-dataroot="/home/gui/dev/t5math/data/amps/mathematica/**/*.txt"
```

in your case.

**Comment by JiwenJ** [comment]
I am confused, what is the meaning of using split("@")
